### ISSUE TITLE
plugins 

### ISSUE THREAD

**Issue by cockjoin** [blockyfish-client/desktop-client#2]
Is it possible to add custom plugins in Blockyfish client version 3.11? What I mean is, will it be possible to create a folder for plugins, similar to older versions of Blockyfish?
![Uploading obraz_2024-01-31_180826241.png…]()

**Comment by nostopgmaming17** [comment]
yes its possible

**Comment by ItsPi3141** [comment]
Please see here  
https://blockyfish.netlify.app/docs/tutorial/testing-and-debugging/#loading-external-plugins
