### ISSUE TITLE
[BUG] Doesn't start on Linux

### ISSUE THREAD

**Issue by ant-7802** [blockyfish-client/desktop-client#4]
whenever I run it using npx electron . or npm run test, it works once and then an hour later it will work again, please release a real linux binary, thanks!

**Comment by ant-7802** [comment]
this would also be good for cb users

**Comment by ItsPi3141** [comment]
Can you check to see if the bug is still present in the latest release?

**Comment by ant-7802** [comment]
Hi, the game loads but then when you try to press play, it doesn't work and just gives "error playing" error

**Comment by ItsPi3141** [comment]
That's most likely an issue with Deeeep.io, not with the client. 

Can you go to https://beta.deeeep.io on your browser and press play? See if it produces the same error.

**Comment by ant-7802** [comment]
bro, it's not an issue with deeeep.io, I can only play it on windows with the blockyfish client, the site works fine and that's what I use because the app doesn't work, I have tested this on THREE different devices

**Comment by mahdi13377** [comment]
download source 
run with npm run test 
check network tab while trying to press play
check the response of the request that gets the host ids (or check if request was sent at all)
also disable api crash bypass if you have it enabled

**Comment by cantevenread** [comment]
run: sudo npm run start

Make sure sudo to allow the program to make connections

**Comment by ant-7802** [comment]
> run: sudo npm run start
> 
> Make sure sudo to allow the program to make connections

running anything in sudo is a bad idea unless it needs it, you dont need sudo to "make connections"

**Comment by cantevenread** [comment]
ok then dont. But please send more information, pictures maybe, video of u building it from source.

**Comment by ant-7802** [comment]
> ok then dont. But please send more information, pictures maybe, video of u building it from source. and the issue

it can easily be reproduced on ANY linux machine

**Comment by M1mron** [comment]
> it can easily be reproduced on ANY linux machine

That problem is only occurring on your Linux machine. In fact, I didn't encounter any issues when running it on Debian. Could you please provide more information?

**Comment by cantevenread** [comment]
i need more information about your machine what flavour of linux and do u
have node installed?

**Comment by ant-7802** [comment]
I've tried it on ChromeOS, Arch, Ubuntu, Debian, all which haven't worked

**Comment by cantevenread** [comment]
Does it open? or just does not let you click play?

**Comment by ant-7802** [comment]
> Does it open? or just does not let you click play?

it works first try, second try it doesnt

**Comment by ant-7802** [comment]
It's fixed now as of 3.2.0, Thank you guys!
